### ISSUE TITLE
microstutter

### ISSUE THREAD

**Issue by Numynum** [cr4ckp0t/ElvUI_SystemDatatext#1]
for some reason I have rather bad microstutters when I use the datatext
every time the fps/memory counter updates, there's a few stutter, which gets worse and worse over time
I'm not sure if it's cause of blizzards code not being able to support monitoring like that, or if there's anything you could do to fix it
but right now it's sadly unusable for me :/
which sucks, cause it's so much better than elvui's default system datatext

**Comment by cr4ckp0t** [comment]
I see what you mean. It looks like it is an issue with Blizzard net code, and there isn't anything I can do about it. ElvUI's system datatext does it as well.
