### ISSUE TITLE
Improved System does not show up in Datatext

### ISSUE THREAD

**Issue by tuseith** [cr4ckp0t/ElvUI_SystemDatatext#3]
As of ElvUI version 11.43, Improved System Datatext does not appear as an option to select in the DataTexts dropdown menu. It is still showing under Plugins by Crackpotx as loaded.

**Comment by cr4ckp0t** [comment]
I am running ElvUI 11.46, and use this datatext every day. It is working and uses the datatext name of "System (Improved)" now.
