### ISSUE TITLE
new update 

### ISSUE THREAD

**Issue by qatre20** [cr4ckp0t/ElvUI_SystemDatatext#4]
hey, i just got the new upate it is working but got this error all the time 2x AceLocale-3.0-6: ElvUI_SystemDatatext: Missing entry for 'System (Improved)'
[string "@ElvUI_SystemDatatext\ElvUI_SystemDatatext-2.2.6.lua"]:549: in main chunk

**Comment by Daveo7** [comment]
Fix by editing ElvUI_SystemDatatext\ElvUI_SystemDatatext.lua and edit line 549.

Change from...

`DT:RegisterDatatext("System (Improved)", nil, {"PLAYER_ENTERING_WORLD"}, OnEvent, OnUpdate, OnClick, OnEnter, OnLeave, L["System (Improved)"])`

to...
`DT:RegisterDatatext("System (Improved)", nil, {"PLAYER_ENTERING_WORLD"}, OnEvent, OnUpdate, OnClick, OnEnter, OnLeave)`

**Comment by qatre20** [comment]
Thank you!
