### ISSUE TITLE
AceLocale Error

### ISSUE THREAD

**Issue by AphelionZero** [cr4ckp0t/ElvUI_SystemDatatext#6]
via Bugsack

91x AceLocale-3.0-6: ElvUI_SystemDatatext: Missing entry for 'System (Improved)'
[string "@ElvUI_SystemDatatext\ElvUI_SystemDatatext-2.2.6.lua"]:549: in main chunk

I disabled all addons but ElvUI, ElvUI_options and SystemDataText and the error persisted.

**Comment by Daveo7** [comment]
Fix by editing ElvUI_SystemDatatext\ElvUI_SystemDatatext.lua and edit line 549.

Change from...

`DT:RegisterDatatext("System (Improved)", nil, {"PLAYER_ENTERING_WORLD"}, OnEvent, OnUpdate, OnClick, OnEnter, OnLeave, L["System (Improved)"])`

to...
`DT:RegisterDatatext("System (Improved)", nil, {"PLAYER_ENTERING_WORLD"}, OnEvent, OnUpdate, OnClick, OnEnter, OnLeave)`

**Comment by AphelionZero** [comment]
Easy fix, thank you very much!
