### ISSUE TITLE
Missing Entry 9.0.1

### ISSUE THREAD

**Issue by Lucetia** [cr4ckp0t/ElvUI_SystemDatatext#7]
I have the updated ElvUI 12 and then I updated ElvUI System Datatext to the one available 13 hours ago (3.0.0.) and when I log in I get this error:

> 16x AceLocale-3.0-6: ElvUI_SystemDatatext: Missing entry for 'System (Improved)'
> 
> [string "@ElvUI_SystemDatatext\ElvUI_SystemDatatext-3.0.0.lua"]:549: in main chunk

The 16x in this case seems to vary each time I log in.

**Comment by cr4ckp0t** [comment]
Thanks for letting me know. This was fixed in 3.0.1.
