### ISSUE TITLE
Missing entry for 'Disable in Combat

### ISSUE THREAD

**Issue by zefrogi** [cr4ckp0t/ElvUI_SystemDatatext#8]
Getting two errors once I open /ec:

```
1x AceLocale-3.0-6: ElvUI_SystemDatatext: Missing entry for 'Disable in Combat'
[string "@ElvUI_SystemDatatext\ElvUI_SystemDatatext-3.0.3.lua"]:550: in function `callback'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1071: in function <ElvUI\Core\Config.lua:1058>
[string "=[C]"]: in function `?'
[string "@Ace3\AceConsole-3.0\AceConsole-3.0-7.lua"]:94: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5093: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4757: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4793: in function <FrameXML\ChatFrame.lua:4789>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

```
1x AceLocale-3.0-6: ElvUI_SystemDatatext: Missing entry for 'Disable showing tooltip in combat.'
[string "@ElvUI_SystemDatatext\ElvUI_SystemDatatext-3.0.3.lua"]:551: in function `callback'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1071: in function <ElvUI\Core\Config.lua:1058>
[string "=[C]"]: in function `?'
[string "@Ace3\AceConsole-3.0\AceConsole-3.0-7.lua"]:94: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5093: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4757: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4793: in function <FrameXML\ChatFrame.lua:4789>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

**Comment by SpookyActionALT64Distance** [comment]
4x AceLocale-3.0-6: ElvUI_SystemDatatext: Missing entry for 'Disable in Combat'
[string "@ElvUI_SystemDatatext\ElvUI_SystemDatatext-3.0.4.lua"]:550: in function <ElvUI_SystemDatatext\ElvUI_SystemDatatext.lua:464>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-37.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1071: in function <ElvUI\Core\Config.lua:1058>
[string "=[C]"]: in function `ToggleOptionsUI'
[string "@ElvUI\init.lua"]:213: in function <ElvUI\init.lua:212>
----------------------------------------------------------------------------------------------------------------------------------------------
4x AceLocale-3.0-6: ElvUI_SystemDatatext: Missing entry for 'Disable showing tooltip in combat.'
[string "@ElvUI_SystemDatatext\ElvUI_SystemDatatext-3.0.4.lua"]:551: in function <ElvUI_SystemDatatext\ElvUI_SystemDatatext.lua:464>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-37.lua"]:167: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:161>
[string "=[C]"]: ?
[string "@ElvUI\Core\Config.lua"]:1071: in function <ElvUI\Core\Config.lua:1058>
[string "=[C]"]: in function `ToggleOptionsUI'
[string "@ElvUI\init.lua"]:213: in function <ElvUI\init.lua:212>
