### ISSUE TITLE
Stutter Issue

### ISSUE THREAD

**Issue by Lysergiic** [cr4ckp0t/ElvUI_SystemDatatext#9]
Hello, I've found an issue that doesn't bring up an error in TBCC. Having it enabled causes a stutter every 2-3 seconds moving. I've noticed it gets worse as the memory builds in the tooltip. 
My guess is a mem-leak or its scanning the memory too often. I'm assuming for the purpose of refreshing the memory feature. 

Testing:
I've had only elvUI, options, and this plugin enabled and the stutter still existed.
Disabled the plugin and the stutter was removed.
This was also done on a fresh install of WoW.

**Comment by cr4ckp0t** [comment]
You are correct, it is because of the memory polling. It happens in retail as well, and exists in the standard System datatext that is included with ElvUI. It is more to do with API issues as opposed to an issue with the addon. There's not really anything I can do about it.
